import {
  Archive,
  ArchiveRestore,
  ArrowDownLeft,
  ArrowDownWideNarrow,
  ArrowUpNarrowWide,
  ArrowUpRight,
  Bed,
  BookOpen,
  Calendar,
  CalendarCheck,
  ChartColumn,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Coffee,
  Coins,
  Eye,
  EyeOff,
  Flame,
  Footprints,
  Gamepad2,
  Gift,
  GlassWater,
  Heart,
  History as HistoryIcon,
  Languages,
  LayoutDashboard,
  ListChecks,
  LogOut,
  Minus,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  Pause,
  Pencil,
  PiggyBank,
  Pizza,
  Play,
  Plus,
  Repeat,
  Search,
  ShoppingBag,
  Snowflake,
  Sparkles,
  Store,
  Sun,
  Tags,
  Target,
  Ticket,
  Trash2,
  TrendingDown,
  TrendingUp,
  Tv,
  Undo2,
  User,
  Wallet,
  X,
} from 'lucide-react'
import type { LucideProps } from 'lucide-react'

const ICONS = {
  wallet: Wallet,
  'arrow-up-narrow-wide': ArrowUpNarrowWide,
  'arrow-down-wide-narrow': ArrowDownWideNarrow,
  'arrow-down-left': ArrowDownLeft,
  'arrow-up-right': ArrowUpRight,
  sun: Sun,
  moon: Moon,
  check: Check,
  x: X,
  user: User,
  'chevron-down': ChevronDown,
  'chevron-up': ChevronUp,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  languages: Languages,
  'log-out': LogOut,
  calendar: Calendar,
  tags: Tags,
  'layout-dashboard': LayoutDashboard,
  'panel-left-close': PanelLeftClose,
  'panel-left-open': PanelLeftOpen,
  plus: Plus,
  search: Search,
  pencil: Pencil,
  'trash-2': Trash2,
  eye: Eye,
  'eye-off': EyeOff,
  'piggy-bank': PiggyBank,
  'chart-column': ChartColumn,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  minus: Minus,
  target: Target,
  repeat: Repeat,
  pause: Pause,
  play: Play,
  'calendar-check': CalendarCheck,
  'list-checks': ListChecks,
  store: Store,
  history: HistoryIcon,
  heart: Heart,
  sparkles: Sparkles,
  coins: Coins,
  snowflake: Snowflake,
  flame: Flame,
  archive: Archive,
  'archive-restore': ArchiveRestore,
  gift: Gift,
  'gamepad-2': Gamepad2,
  coffee: Coffee,
  tv: Tv,
  pizza: Pizza,
  bed: Bed,
  'shopping-bag': ShoppingBag,
  ticket: Ticket,
  'undo-2': Undo2,
  'glass-water': GlassWater,
  'book-open': BookOpen,
  footprints: Footprints,
} as const

export type IconName = keyof typeof ICONS

interface IconProps extends Omit<LucideProps, 'size' | 'strokeWidth'> {
  name: IconName
  size?: number
  strokeWidth?: number
}

function Icon({ name, size = 16, strokeWidth = 1.5, ...rest }: IconProps) {
  const LucideIcon = ICONS[name]
  return <LucideIcon size={size} strokeWidth={strokeWidth} {...rest} />
}

export default Icon
